#!/usr/bin/env python3
"""
Omni-Shield Claude Annotation Pipeline
========================================
Stage 2 of the knowledge distillation pipeline.

Takes the synthetic ID card images generated by generate_synthetic_ids.py
and sends each one to Claude claude-sonnet-4-20250514 for rich PII annotation.
Claude's response becomes the "teacher" signal that we use to fine-tune
the local Qwen2-VL-2B model.

WHY WE STILL ANNOTATE WITH CLAUDE EVEN THOUGH WE HAVE GROUND TRUTH:
The synthetic generator already knows exactly where every text field is,
so technically we have perfect annotations. However, Claude's annotations
add three things the generator cannot provide:

1. Richer semantic understanding — Claude knows that "DUPS: 00" is NOT
   PII but "99 999 999" next to "IDN" IS PII. The generator marks
   every field it renders; Claude distinguishes PII from non-PII.

2. Face and signature detection practice — the model learns to look
   for photo zones and cursive regions, not just text, which is exactly
   the capability gap we're trying to close.

3. Natural language reasoning — Claude's output includes a "reasoning"
   field explaining WHY each item is PII. We can optionally include
   this in the fine-tuning data as chain-of-thought supervision, which
   dramatically improves a small model's generalisation ability.

The output of this script is a JSONL file (one JSON object per line)
in the Qwen2-VL fine-tuning format, ready to feed directly into
the train_vlm.py QLoRA training script.

Usage:
    export ANTHROPIC_API_KEY="sk-ant-..."
    python annotate_with_claude.py \
        --dataset_dir ./dataset \
        --output_file ./dataset/train.jsonl \
        --max_cards 500

Cost estimate:
    Each image costs roughly 800-1200 input tokens (image) + 300-500
    output tokens (JSON annotation). At claude-sonnet-4 pricing that
    is approximately $0.004-0.008 per card. 1000 cards ≈ $5-8 USD.
"""

import argparse
import base64
import json
import os
import time
from pathlib import Path

import anthropic

# ══════════════════════════════════════════════════════════════════════════════
# ANNOTATION PROMPT
# This is the same prompt used in ClaudeVisionAgent in the live pipeline.
# Using the same prompt for both annotation and inference means the model
# learns to produce outputs that the pipeline parser can already handle.
# ══════════════════════════════════════════════════════════════════════════════
ANNOTATION_PROMPT = """You are a PII detection expert annotating identity documents for a privacy protection system.

Examine this identity document image carefully. Identify EVERY piece of personal identifiable information (PII) visible in the image.

Categories to detect — be exhaustive:
- Full name, surname, given name (both printed and handwritten)
- Date of birth (any date clearly associated with a person's birth)
- ID numbers: national ID, driver licence number, Aadhaar, PAN, passport, document discriminator (DD), any alphanumeric identifier that uniquely identifies a person
- Physical address: street, suburb, city, state, postcode/zip
- Phone number, email, URL
- Face photographs (any visible human face or photo zone, including small thumbnails)
- Handwritten signatures (any cursive or handwritten mark in a signature box)
- Biometric or physical descriptor fields (height, weight, eye colour) — these ARE PII

Fields that are NOT PII (do not include these):
- Expiry date (EXP, 4b) — this is document metadata, not personal information
- Issue date (ISS, 4a) — same reason
- Document class / vehicle class / endorsements / restrictions
- "ORGAN DONOR" text
- The document title ("DRIVER LICENSE", "AADHAAR", etc.)
- Issuing authority name / government department name
- State or country name used as a header

For AAMVA (North American) licence abbreviations:
  IS PII: IDN (ID number), DL (licence number), DLN, DD (document discriminator), 2 (name), 3 (DOB), 8 (address)
  NOT PII: 4a ISS, 4b EXP, 15 SEX, 18 EYES, 16 HGT, DUPS, CLASS, END, RST

Output a JSON array and absolutely nothing else — no markdown, no explanation, no preamble.
Each item must have exactly these fields:
{
  "label": "human-readable field name e.g. Full Name, ID Number, Face, Signature, Date of Birth",
  "value": "exact text value, or 'face' for photo zones, or 'signature' for signature areas",
  "box_2d": [ymin, xmin, ymax, xmax],
  "reasoning": "one sentence explaining why this is PII"
}

Coordinates are integers normalized to the range [0, 1000] where (0,0) is the top-left corner and (1000,1000) is the bottom-right corner. Make bounding boxes tight around the actual content.

Output ONLY the JSON array. Nothing before it, nothing after it."""


def encode_image_base64(image_path: str) -> tuple[str, str]:
    """
    Encode an image file as base64 for the Anthropic API.
    Returns (base64_data, media_type).
    """
    path = Path(image_path)
    suffix = path.suffix.lower()
    media_type_map = {
        ".png":  "image/png",
        ".jpg":  "image/jpeg",
        ".jpeg": "image/jpeg",
        ".webp": "image/webp",
    }
    media_type = media_type_map.get(suffix, "image/png")
    with open(image_path, "rb") as f:
        data = base64.standard_b64encode(f.read()).decode("utf-8")
    return data, media_type


def annotate_image(
    client: anthropic.Anthropic,
    image_path: str,
    model: str = "claude-sonnet-4-20250514",
    max_retries: int = 3,
) -> list[dict] | None:
    """
    Send one image to Claude and parse its PII annotation response.

    Returns a list of annotation dicts, or None if the call failed after
    all retries.

    Retry logic: Claude's API occasionally returns a 529 (overload) or
    rate-limit error. We back off exponentially and retry up to max_retries
    times before giving up on that image. Failed images are logged to a
    separate failures file so you can re-run just those images later.
    """
    image_data, media_type = encode_image_base64(image_path)

    for attempt in range(max_retries):
        try:
            response = client.messages.create(
                model=model,
                max_tokens=2048,
                messages=[
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "image",
                                "source": {
                                    "type": "base64",
                                    "media_type": media_type,
                                    "data": image_data,
                                },
                            },
                            {
                                "type": "text",
                                "text": ANNOTATION_PROMPT,
                            },
                        ],
                    }
                ],
            )

            raw_text = response.content[0].text.strip()

            # Strip markdown code fences if Claude wraps the JSON despite instructions
            if raw_text.startswith("```"):
                raw_text = raw_text.split("```")[1]
                if raw_text.startswith("json"):
                    raw_text = raw_text[4:]
                raw_text = raw_text.strip()

            annotations = json.loads(raw_text)

            # Validate structure — each item must have the required fields
            validated = []
            for item in annotations:
                if not all(k in item for k in ("label", "value", "box_2d")):
                    continue
                box = item["box_2d"]
                if len(box) != 4 or not all(isinstance(c, (int, float)) for c in box):
                    continue
                # Clamp coordinates to [0, 1000]
                item["box_2d"] = [
                    max(0, min(1000, int(box[0]))),  # ymin
                    max(0, min(1000, int(box[1]))),  # xmin
                    max(0, min(1000, int(box[2]))),  # ymax
                    max(0, min(1000, int(box[3]))),  # xmax
                ]
                validated.append(item)

            return validated

        except json.JSONDecodeError as e:
            print(f"    JSON parse error on attempt {attempt+1}: {e}")
            print(f"    Raw response: {raw_text[:200]}...")
            if attempt < max_retries - 1:
                time.sleep(2 ** attempt)

        except anthropic.RateLimitError:
            wait = 30 * (attempt + 1)
            print(f"    Rate limited. Waiting {wait}s ...")
            time.sleep(wait)

        except anthropic.APIStatusError as e:
            print(f"    API error {e.status_code} on attempt {attempt+1}: {e.message}")
            if e.status_code == 529:
                time.sleep(10 * (attempt + 1))
            else:
                return None

        except Exception as e:
            print(f"    Unexpected error: {e}")
            if attempt < max_retries - 1:
                time.sleep(2)

    return None


def annotation_to_vlm_training_sample(
    image_path: str,
    claude_annotations: list[dict],
    ground_truth: dict,
) -> dict:
    """
    Convert Claude's annotations into the Qwen2-VL fine-tuning format.

    Qwen2-VL expects a conversation format:
    {
        "image": "<path or base64>",
        "conversations": [
            {"from": "human", "value": "<prompt>"},
            {"from": "gpt", "value": "<expected model output>"}
        ]
    }

    The "gpt" value is what we want the fine-tuned model to learn to
    produce when shown the same prompt. We format it as the structured
    JSON list Claude produced, which means the model learns to output
    the same structured format that our pipeline parser already handles.

    We also include a chain-of-thought version (with reasoning) as an
    optional second training sample — this helps small models generalise
    by teaching them to reason step by step rather than just pattern-match.
    """
    # Format Claude's annotations as the target output string
    # We include only label, value, box_2d (not reasoning) for the main sample
    # so the model learns the same output format as the live pipeline
    output_items = [
        {
            "label": a["label"],
            "value": a["value"],
            "box_2d": a["box_2d"],
        }
        for a in claude_annotations
    ]
    target_output = json.dumps(output_items, indent=2)

    # Chain-of-thought version includes reasoning
    cot_items = [
        {
            "label": a["label"],
            "value": a["value"],
            "box_2d": a["box_2d"],
            "reasoning": a.get("reasoning", ""),
        }
        for a in claude_annotations
    ]
    cot_output = json.dumps(cot_items, indent=2)

    # The instruction prompt — identical to what the live pipeline sends
    instruction = (
        "You are a PII detection expert. Examine this identity document "
        "and identify every piece of personal identifiable information. "
        "Output a JSON array with label, value, and box_2d (normalized "
        "0-1000 coordinates [ymin, xmin, ymax, xmax]) for each item. "
        "Output ONLY the JSON array."
    )

    return {
        "image": image_path,
        "country": ground_truth.get("country", "unknown"),
        "card_type": ground_truth.get("card_type", "unknown"),
        "image_id": ground_truth.get("image_id", ""),
        "conversations": [
            {"from": "human", "value": instruction},
            {"from": "gpt",   "value": target_output},
        ],
        # Chain-of-thought variant stored separately for optional CoT training
        "conversations_cot": [
            {"from": "human", "value": instruction + " Include a 'reasoning' field explaining why each item is PII."},
            {"from": "gpt",   "value": cot_output},
        ],
        # Ground truth from the generator, for evaluation / sanity checking
        "ground_truth_pii_count": len(ground_truth.get("fields", [])),
        "claude_pii_count": len(claude_annotations),
    }


def main():
    parser = argparse.ArgumentParser(
        description="Annotate synthetic ID card images using Claude API"
    )
    parser.add_argument("--dataset_dir", type=str, required=True,
        help="Dataset directory produced by generate_synthetic_ids.py")
    parser.add_argument("--output_file", type=str, default=None,
        help="Output JSONL file path (default: dataset_dir/train.jsonl)")
    parser.add_argument("--max_cards", type=int, default=None,
        help="Maximum number of cards to annotate (default: all)")
    parser.add_argument("--model", type=str, default="claude-sonnet-4-20250514",
        help="Claude model to use for annotation")
    parser.add_argument("--resume", action="store_true",
        help="Skip cards already in the output file (for resuming interrupted runs)")
    parser.add_argument("--delay_ms", type=int, default=500,
        help="Delay in milliseconds between API calls (rate limit management)")
    args = parser.parse_args()

    # Validate API key
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY environment variable not set.")
        print("  export ANTHROPIC_API_KEY='sk-ant-...'")
        return

    client = anthropic.Anthropic(api_key=api_key)

    dataset_dir = Path(args.dataset_dir)
    output_file = Path(args.output_file) if args.output_file else dataset_dir / "train.jsonl"
    failures_file = dataset_dir / "annotation_failures.json"

    # Load manifest
    manifest_path = dataset_dir / "manifest.json"
    if not manifest_path.exists():
        print(f"ERROR: No manifest.json found in {dataset_dir}")
        print("  Run generate_synthetic_ids.py first.")
        return

    manifest = json.loads(manifest_path.read_text())
    cards = manifest["cards"]
    if args.max_cards:
        cards = cards[:args.max_cards]

    print(f"Dataset: {len(cards)} cards across {len(set(c['country'] for c in cards))} countries")
    print(f"Model: {args.model}")
    print(f"Output: {output_file}")

    # Resume: find already-annotated image IDs
    already_done = set()
    if args.resume and output_file.exists():
        with open(output_file) as f:
            for line in f:
                try:
                    sample = json.loads(line)
                    already_done.add(sample.get("image_id", ""))
                except json.JSONDecodeError:
                    pass
        print(f"Resuming: {len(already_done)} cards already annotated, skipping them.")

    failures = []
    success_count = 0
    skip_count = 0

    with open(output_file, "a" if args.resume else "w") as out_f:
        for i, card in enumerate(cards):
            image_id = card["image_id"]

            if image_id in already_done:
                skip_count += 1
                continue

            # Load ground truth annotation
            ann_path = card.get("annotation_path")
            if not ann_path or not Path(ann_path).exists():
                print(f"  [{i+1}/{len(cards)}] SKIP: no annotation file for {image_id}")
                continue

            ground_truth = json.loads(Path(ann_path).read_text())
            image_path = card["image_path"]

            if not Path(image_path).exists():
                print(f"  [{i+1}/{len(cards)}] SKIP: image not found: {image_path}")
                continue

            print(f"  [{i+1}/{len(cards)}] {card['country']} {card['card_type']} — {image_id[:8]}...")

            # Call Claude
            annotations = annotate_image(client, image_path, model=args.model)

            if annotations is None:
                print(f"    FAILED after retries")
                failures.append(card)
                continue

            print(f"    Claude found {len(annotations)} PII items "
                  f"(ground truth had {len(ground_truth.get('fields', []))})")

            # Convert to training sample
            sample = annotation_to_vlm_training_sample(
                image_path, annotations, ground_truth
            )

            # Write to JSONL (one JSON object per line)
            out_f.write(json.dumps(sample) + "\n")
            out_f.flush()   # Flush after every card so we can resume safely

            success_count += 1

            # Rate limit management
            if args.delay_ms > 0:
                time.sleep(args.delay_ms / 1000.0)

    # Save failures list for re-running
    if failures:
        failures_file.write_text(json.dumps(failures, indent=2))
        print(f"\n{len(failures)} cards failed — saved to {failures_file}")
        print(f"Re-run failed cards with:")
        print(f"  python annotate_with_claude.py --dataset_dir {dataset_dir} --resume")

    print(f"\nAnnotation complete:")
    print(f"  Annotated: {success_count}")
    print(f"  Skipped (resume): {skip_count}")
    print(f"  Failed: {len(failures)}")
    print(f"  Output: {output_file}")
    print(f"\nNext step: run train_vlm.py to fine-tune Qwen2-VL on this dataset")
    print(f"  python train_vlm.py --train_file {output_file}")


if __name__ == "__main__":
    main()
